runtime: nodejs18
env_variables:
  PORT: "3000"
  JWT_SECRET: "hahahahaha"
  DB_CONNECTION_NAME: "smart-fish-feeder-394209:asia-southeast2:db-sff"
  DB_USER: "postgres"
  DB_PASSWORD: "090909"
  DB_NAME: "db-sff-backend"
  DB_IP_TYPE: "PUBLIC"
